name: "Arkistoija"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 28 12 *" # We do not want to run in January because then the year for photo release is not the correct one

jobs:
  arkistoi:
    name: "Arkistoi vanhat kuvat"
    runs-on: "ubuntu-latest"

    steps:
      - name: Tarkasta vuosi
        id: date
        run: echo "::set-output name=vuosi::$(date +'%Y')"
      - name: "Arkistoi kuvat"
        run: |
          echo "Arkistoitu!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.date.outputs.vuosi }}
          prerelease: false
          title: Vuoden ${{ steps.date.outputs.vuosi }} kuvat
          files: |
            kuvat/*

  pyyhi:
    name: "Pyyhi vanhat kuvat"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: master

      - name: Poista vanhat kuvat ja päivitä Githubiin
        uses: EndBug/add-and-commit@v7
        with:
          message: Poistettu vanhat kuvat
          committer_name: GitHub Actions
          committer_email: actions@github.com
          remove: 'kuvat/*'