name: "Arkistoija"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 1 *"

jobs:
  arkistoi:
    name: "Arkistoi vanhat kuvat"
    runs-on: "ubuntu-latest"

    steps:
      - name: Tarkasta vuosi
        id: date
        run: echo "::set-output name=vuosi::$(date +'%Y')"
      - name: "Arkistoi kuvat"
        run: |
          echo "Arkistoitu!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: latest
          prerelease: false
          title: Vuoden ${{ steps.date.outputs.vuosi }} kuvat
          files: |
            kuvat/*
